apiVersion: batch/v1
kind: Job
metadata:
  name: nats-subscriber
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: subscriber
          image: jrebaza01/nats-subscriber:IMAGE_TAG
          imagePullPolicy: Always
